spring:
  application:
    name: "lucas"
  profiles:
    active: test

server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /api
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /public/swagger